Do not make checksums of checksums
Ouranosinc/raven-testdata pull request #4
Opened 2020-12-11 14:47 UTC by Zeitsperre

Fixes #3

2020-12-11 16:39 UTC, huard requested changes

2020-12-11 16:39 UTC, huard commented on make_check_sums.py
>          if f.is_file() and not Path(outf).exists():
I suggest you review this logic instead. Ie remplace the file suffix by md5, then check if it exists.

2020-12-11 21:00 UTC, huard reviewed
Every md5 will be regenerated. Won't git think that all the md5 files were changed ? 
In the loop, 
#. if suffix == ".md5" continue
#. if file + ".md5" does not exist create checksum

2020-12-11 21:07 UTC, Zeitsperre commented
In the initial case, they were regenerated, but because there are no changes (the `.md5` string doesn't change), they're seen as the exact same file, so they're ignored by git.

I'm still a bit lost as I thought that the logic in my initial commit to skip the processing of files with existing `.md5` accompanying files was enough, ie:
```
...
if f.parent.name != "raven-testdata" and not str(f).endswith(".md5")
)

Am I missing something?
```

2020-12-11 21:33 UTC, huard commented
1. I thought it was weird to use Path object, but then use string.endswith to check the suffix.
2. The list comprehension bundles a lot of stuff (glob pattern + two logical conditions). Also why the parent.name condition ? 

So basically, my comment is "make the logic stand-out", this way, we won't trip ourselves in it. This is a trivial example, but this is useful everywhere.

2020-12-11 22:08 UTC, Zeitsperre commented
>     1. I thought it was weird to use Path object, but then use string.endswith to check the suffix.

That's reasonable. I think Path().suffix is probably fine as well. I can integrate that into this PR.

>     2. The list comprehension bundles a lot of stuff (glob pattern + two logical conditions)

I can pull the logic out of there if we want. It's a useful aspect of lost comprehensions, so I figured why not use it. The alternative I have in mind is to find all objects that end with md5 and all those that don't (and are not folders), sanitize the `".md5"` from the `.md5` files, turn them into sets and then make `.md5` files on the non-`.md5` files that differ between them. Would that be closer to what you were envisioning ?

> Also why the parent.name condition ?

If that isn't there, we end up making pointless `.md5` files for the top-level files (e.g. `make_check_sums.py.md5`).

2020-12-14 14:50 UTC, huard commented
1. OK
2. I love list comprehensions, but they quickly get unclear if you include too many logical conditions. Yes. 

ok

2020-12-14 19:16 UTC, Zeitsperre commented
Good to go?

2020-12-14 20:07 UTC, huard commented
The code created checksums for hidden files (.e.g. .git).

2020-12-14 20:07 UTC, huard approved these changes

2020-12-14 20:07 UTC, merged

2020-12-14 20:10 UTC, Zeitsperre commented
Wow, I didn't even realize. My bad!